apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          valueFrom: 
            configMapKeyRef:
              name: my-configmap
              key: mysqldbname
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        name: mysqldb
        image: mysql:8
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: my-dv
        ports:
        - containerPort: 3306
      volumes:
      - name: my-dv
        persistentVolumeClaim:
          claimName: ebs-claim
