apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybank-jdbc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mybank-jdbc
  template:
    metadata:
      labels:
        app: mybank-jdbc
    spec:
      containers:
      - name: mybank-jdbc
        image: mehar221/my-img
        ports:
        - containerPort: 8080
      restartPolicy: Always
